import { MigrationInterface, QueryRunner } from "typeorm";

export class FixColumnNames1745856036890 implements MigrationInterface {
    name = 'FixColumnNames1745856036890'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "userId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "temporary_posts"("id", "content", "userId", "createdAt", "updatedAt") SELECT "id", "content", "userId", "createdAt", "updatedAt" FROM "posts"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`ALTER TABLE "temporary_posts" RENAME TO "posts"`);
        await queryRunner.query(`CREATE TABLE "temporary_follows" ("followerId" integer NOT NULL, "followingId" integer NOT NULL, PRIMARY KEY ("followerId", "followingId"))`);
        await queryRunner.query(`INSERT INTO "temporary_follows"("followerId", "followingId") SELECT "followerId", "followingId" FROM "follows"`);
        await queryRunner.query(`DROP TABLE "follows"`);
        await queryRunner.query(`ALTER TABLE "temporary_follows" RENAME TO "follows"`);
        await queryRunner.query(`CREATE TABLE "temporary_likes" ("postId" integer NOT NULL, "userId" integer NOT NULL, PRIMARY KEY ("postId", "userId"))`);
        await queryRunner.query(`INSERT INTO "temporary_likes"("postId", "userId") SELECT "postId", "userId" FROM "likes"`);
        await queryRunner.query(`DROP TABLE "likes"`);
        await queryRunner.query(`ALTER TABLE "temporary_likes" RENAME TO "likes"`);
        await queryRunner.query(`CREATE TABLE "temporary_post_hashtags_hashtags" ("postId" integer NOT NULL, "hashtagId" integer NOT NULL, PRIMARY KEY ("postId", "hashtagId"))`);
        await queryRunner.query(`INSERT INTO "temporary_post_hashtags_hashtags"("postId", "hashtagId") SELECT "postId", "hashtagId" FROM "post_hashtags_hashtags"`);
        await queryRunner.query(`DROP TABLE "post_hashtags_hashtags"`);
        await queryRunner.query(`ALTER TABLE "temporary_post_hashtags_hashtags" RENAME TO "post_hashtags_hashtags"`);
        await queryRunner.query(`CREATE TABLE "temporary_likes" ()`);
        await queryRunner.query(`INSERT INTO "temporary_likes"() SELECT  FROM "likes"`);
        await queryRunner.query(`DROP TABLE "likes"`);
        await queryRunner.query(`ALTER TABLE "temporary_likes" RENAME TO "likes"`);
        await queryRunner.query(`CREATE TABLE "temporary_likes" ("postsId" integer NOT NULL, "usersId" integer NOT NULL, PRIMARY KEY ("postsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "temporary_likes"() SELECT  FROM "likes"`);
        await queryRunner.query(`DROP TABLE "likes"`);
        await queryRunner.query(`ALTER TABLE "temporary_likes" RENAME TO "likes"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar(255) NOT NULL, "firstName" varchar(255) NOT NULL, "lastName" varchar(255) NOT NULL, "email" varchar(255) NOT NULL, "password" varchar NOT NULL, "bio" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "firstName", "lastName", "email", "password", "bio", "createdAt", "updatedAt") SELECT "id", "username", "firstName", "lastName", "email", "password", "bio", "createdAt", "updatedAt" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "temporary_hashtags" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_7fedde18872deb14e4889361d7b" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "temporary_hashtags"("id", "name", "createdAt") SELECT "id", "name", "createdAt" FROM "hashtags"`);
        await queryRunner.query(`DROP TABLE "hashtags"`);
        await queryRunner.query(`ALTER TABLE "temporary_hashtags" RENAME TO "hashtags"`);
        await queryRunner.query(`CREATE TABLE "temporary_posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "userId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "temporary_posts"("id", "content", "userId", "createdAt", "updatedAt") SELECT "id", "content", "userId", "createdAt", "updatedAt" FROM "posts"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`ALTER TABLE "temporary_posts" RENAME TO "posts"`);
        await queryRunner.query(`CREATE INDEX "IDX_fdb91868b03a2040db408a5333" ON "follows" ("followerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef463dd9a2ce0d673350e36e0f" ON "follows" ("followingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_376f9c48925cfe81125f0a8715" ON "likes" ("postsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5312be6de5784293ac2908978" ON "likes" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_23256a4f830e009e7f9ebaef70" ON "post_hashtags_hashtags" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1512fd06e704477d4027087e8d" ON "post_hashtags_hashtags" ("hashtagId") `);
        await queryRunner.query(`CREATE TABLE "temporary_posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "userId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_ae05faaa55c866130abef6e1fee" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_posts"("id", "content", "userId", "createdAt", "updatedAt") SELECT "id", "content", "userId", "createdAt", "updatedAt" FROM "posts"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`ALTER TABLE "temporary_posts" RENAME TO "posts"`);
        await queryRunner.query(`DROP INDEX "IDX_fdb91868b03a2040db408a5333"`);
        await queryRunner.query(`DROP INDEX "IDX_ef463dd9a2ce0d673350e36e0f"`);
        await queryRunner.query(`CREATE TABLE "temporary_follows" ("followerId" integer NOT NULL, "followingId" integer NOT NULL, CONSTRAINT "FK_fdb91868b03a2040db408a53331" FOREIGN KEY ("followerId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb" FOREIGN KEY ("followingId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("followerId", "followingId"))`);
        await queryRunner.query(`INSERT INTO "temporary_follows"("followerId", "followingId") SELECT "followerId", "followingId" FROM "follows"`);
        await queryRunner.query(`DROP TABLE "follows"`);
        await queryRunner.query(`ALTER TABLE "temporary_follows" RENAME TO "follows"`);
        await queryRunner.query(`CREATE INDEX "IDX_fdb91868b03a2040db408a5333" ON "follows" ("followerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef463dd9a2ce0d673350e36e0f" ON "follows" ("followingId") `);
        await queryRunner.query(`DROP INDEX "IDX_376f9c48925cfe81125f0a8715"`);
        await queryRunner.query(`DROP INDEX "IDX_d5312be6de5784293ac2908978"`);
        await queryRunner.query(`CREATE TABLE "temporary_likes" ("postsId" integer NOT NULL, "usersId" integer NOT NULL, CONSTRAINT "FK_376f9c48925cfe81125f0a87152" FOREIGN KEY ("postsId") REFERENCES "posts" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_d5312be6de5784293ac29089784" FOREIGN KEY ("usersId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("postsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "temporary_likes"("postsId", "usersId") SELECT "postsId", "usersId" FROM "likes"`);
        await queryRunner.query(`DROP TABLE "likes"`);
        await queryRunner.query(`ALTER TABLE "temporary_likes" RENAME TO "likes"`);
        await queryRunner.query(`CREATE INDEX "IDX_376f9c48925cfe81125f0a8715" ON "likes" ("postsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5312be6de5784293ac2908978" ON "likes" ("usersId") `);
        await queryRunner.query(`DROP INDEX "IDX_23256a4f830e009e7f9ebaef70"`);
        await queryRunner.query(`DROP INDEX "IDX_1512fd06e704477d4027087e8d"`);
        await queryRunner.query(`CREATE TABLE "temporary_post_hashtags_hashtags" ("postId" integer NOT NULL, "hashtagId" integer NOT NULL, CONSTRAINT "FK_23256a4f830e009e7f9ebaef707" FOREIGN KEY ("postId") REFERENCES "posts" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_1512fd06e704477d4027087e8de" FOREIGN KEY ("hashtagId") REFERENCES "hashtags" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("postId", "hashtagId"))`);
        await queryRunner.query(`INSERT INTO "temporary_post_hashtags_hashtags"("postId", "hashtagId") SELECT "postId", "hashtagId" FROM "post_hashtags_hashtags"`);
        await queryRunner.query(`DROP TABLE "post_hashtags_hashtags"`);
        await queryRunner.query(`ALTER TABLE "temporary_post_hashtags_hashtags" RENAME TO "post_hashtags_hashtags"`);
        await queryRunner.query(`CREATE INDEX "IDX_23256a4f830e009e7f9ebaef70" ON "post_hashtags_hashtags" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1512fd06e704477d4027087e8d" ON "post_hashtags_hashtags" ("hashtagId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_1512fd06e704477d4027087e8d"`);
        await queryRunner.query(`DROP INDEX "IDX_23256a4f830e009e7f9ebaef70"`);
        await queryRunner.query(`ALTER TABLE "post_hashtags_hashtags" RENAME TO "temporary_post_hashtags_hashtags"`);
        await queryRunner.query(`CREATE TABLE "post_hashtags_hashtags" ("postId" integer NOT NULL, "hashtagId" integer NOT NULL, PRIMARY KEY ("postId", "hashtagId"))`);
        await queryRunner.query(`INSERT INTO "post_hashtags_hashtags"("postId", "hashtagId") SELECT "postId", "hashtagId" FROM "temporary_post_hashtags_hashtags"`);
        await queryRunner.query(`DROP TABLE "temporary_post_hashtags_hashtags"`);
        await queryRunner.query(`CREATE INDEX "IDX_1512fd06e704477d4027087e8d" ON "post_hashtags_hashtags" ("hashtagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_23256a4f830e009e7f9ebaef70" ON "post_hashtags_hashtags" ("postId") `);
        await queryRunner.query(`DROP INDEX "IDX_d5312be6de5784293ac2908978"`);
        await queryRunner.query(`DROP INDEX "IDX_376f9c48925cfe81125f0a8715"`);
        await queryRunner.query(`ALTER TABLE "likes" RENAME TO "temporary_likes"`);
        await queryRunner.query(`CREATE TABLE "likes" ("postsId" integer NOT NULL, "usersId" integer NOT NULL, PRIMARY KEY ("postsId", "usersId"))`);
        await queryRunner.query(`INSERT INTO "likes"("postsId", "usersId") SELECT "postsId", "usersId" FROM "temporary_likes"`);
        await queryRunner.query(`DROP TABLE "temporary_likes"`);
        await queryRunner.query(`CREATE INDEX "IDX_d5312be6de5784293ac2908978" ON "likes" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_376f9c48925cfe81125f0a8715" ON "likes" ("postsId") `);
        await queryRunner.query(`DROP INDEX "IDX_ef463dd9a2ce0d673350e36e0f"`);
        await queryRunner.query(`DROP INDEX "IDX_fdb91868b03a2040db408a5333"`);
        await queryRunner.query(`ALTER TABLE "follows" RENAME TO "temporary_follows"`);
        await queryRunner.query(`CREATE TABLE "follows" ("followerId" integer NOT NULL, "followingId" integer NOT NULL, PRIMARY KEY ("followerId", "followingId"))`);
        await queryRunner.query(`INSERT INTO "follows"("followerId", "followingId") SELECT "followerId", "followingId" FROM "temporary_follows"`);
        await queryRunner.query(`DROP TABLE "temporary_follows"`);
        await queryRunner.query(`CREATE INDEX "IDX_ef463dd9a2ce0d673350e36e0f" ON "follows" ("followingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdb91868b03a2040db408a5333" ON "follows" ("followerId") `);
        await queryRunner.query(`ALTER TABLE "posts" RENAME TO "temporary_posts"`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "userId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "posts"("id", "content", "userId", "createdAt", "updatedAt") SELECT "id", "content", "userId", "createdAt", "updatedAt" FROM "temporary_posts"`);
        await queryRunner.query(`DROP TABLE "temporary_posts"`);
        await queryRunner.query(`DROP INDEX "IDX_1512fd06e704477d4027087e8d"`);
        await queryRunner.query(`DROP INDEX "IDX_23256a4f830e009e7f9ebaef70"`);
        await queryRunner.query(`DROP INDEX "IDX_d5312be6de5784293ac2908978"`);
        await queryRunner.query(`DROP INDEX "IDX_376f9c48925cfe81125f0a8715"`);
        await queryRunner.query(`DROP INDEX "IDX_ef463dd9a2ce0d673350e36e0f"`);
        await queryRunner.query(`DROP INDEX "IDX_fdb91868b03a2040db408a5333"`);
        await queryRunner.query(`ALTER TABLE "posts" RENAME TO "temporary_posts"`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "userId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "posts"("id", "content", "userId", "createdAt", "updatedAt") SELECT "id", "content", "userId", "createdAt", "updatedAt" FROM "temporary_posts"`);
        await queryRunner.query(`DROP TABLE "temporary_posts"`);
        await queryRunner.query(`ALTER TABLE "hashtags" RENAME TO "temporary_hashtags"`);
        await queryRunner.query(`CREATE TABLE "hashtags" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "UQ_7fedde18872deb14e4889361d7b" UNIQUE ("name"))`);
        await queryRunner.query(`INSERT INTO "hashtags"("id", "name", "createdAt") SELECT "id", "name", "createdAt" FROM "temporary_hashtags"`);
        await queryRunner.query(`DROP TABLE "temporary_hashtags"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar(255), "firstName" varchar(255) NOT NULL, "lastName" varchar(255) NOT NULL, "email" varchar(255) NOT NULL, "password" varchar(255), "bio" text, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "firstName", "lastName", "email", "password", "bio", "createdAt", "updatedAt") SELECT "id", "username", "firstName", "lastName", "email", "password", "bio", "createdAt", "updatedAt" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`ALTER TABLE "likes" RENAME TO "temporary_likes"`);
        await queryRunner.query(`CREATE TABLE "likes" ()`);
        await queryRunner.query(`INSERT INTO "likes"() SELECT  FROM "temporary_likes"`);
        await queryRunner.query(`DROP TABLE "temporary_likes"`);
        await queryRunner.query(`ALTER TABLE "likes" RENAME TO "temporary_likes"`);
        await queryRunner.query(`CREATE TABLE "likes" ("postId" integer NOT NULL, "userId" integer NOT NULL, PRIMARY KEY ("postId", "userId"))`);
        await queryRunner.query(`INSERT INTO "likes"() SELECT  FROM "temporary_likes"`);
        await queryRunner.query(`DROP TABLE "temporary_likes"`);
        await queryRunner.query(`ALTER TABLE "post_hashtags_hashtags" RENAME TO "temporary_post_hashtags_hashtags"`);
        await queryRunner.query(`CREATE TABLE "post_hashtags_hashtags" ("postId" integer NOT NULL, "hashtagId" integer NOT NULL, CONSTRAINT "FK_1512fd06e704477d4027087e8de" FOREIGN KEY ("hashtagId") REFERENCES "hashtags" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_23256a4f830e009e7f9ebaef707" FOREIGN KEY ("postId") REFERENCES "posts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("postId", "hashtagId"))`);
        await queryRunner.query(`INSERT INTO "post_hashtags_hashtags"("postId", "hashtagId") SELECT "postId", "hashtagId" FROM "temporary_post_hashtags_hashtags"`);
        await queryRunner.query(`DROP TABLE "temporary_post_hashtags_hashtags"`);
        await queryRunner.query(`ALTER TABLE "likes" RENAME TO "temporary_likes"`);
        await queryRunner.query(`CREATE TABLE "likes" ("postId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "FK_cfd8e81fac09d7339a32e57d904" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_e2fe567ad8d305fefc918d44f50" FOREIGN KEY ("postId") REFERENCES "posts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("postId", "userId"))`);
        await queryRunner.query(`INSERT INTO "likes"("postId", "userId") SELECT "postId", "userId" FROM "temporary_likes"`);
        await queryRunner.query(`DROP TABLE "temporary_likes"`);
        await queryRunner.query(`ALTER TABLE "follows" RENAME TO "temporary_follows"`);
        await queryRunner.query(`CREATE TABLE "follows" ("followerId" integer NOT NULL, "followingId" integer NOT NULL, CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb" FOREIGN KEY ("followingId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_fdb91868b03a2040db408a53331" FOREIGN KEY ("followerId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("followerId", "followingId"))`);
        await queryRunner.query(`INSERT INTO "follows"("followerId", "followingId") SELECT "followerId", "followingId" FROM "temporary_follows"`);
        await queryRunner.query(`DROP TABLE "temporary_follows"`);
        await queryRunner.query(`ALTER TABLE "posts" RENAME TO "temporary_posts"`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "userId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "FK_ae05faaa55c866130abef6e1fee" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "posts"("id", "content", "userId", "createdAt", "updatedAt") SELECT "id", "content", "userId", "createdAt", "updatedAt" FROM "temporary_posts"`);
        await queryRunner.query(`DROP TABLE "temporary_posts"`);
    }

}
